version: '3'

services:
  tpsserver:
    image: tps-tpsserver:1.0.0
    ports:
      - "9000:9000"
      - "9005:9005"
    volumes:
      - /opt/tftpboot:/tftpboot
      - /opt/tps/conf/tpsserver-prod.service:/etc/systemd/system/tpsserver-prod.service
      - /opt/tps/conf/tpsserver-alpha.service:/etc/systemd/system/tpsserver-alpha.service
    restart: always
    tty: true
    privileged: true

  httpd:
    image: tps-httpd:1.0.0
    ports:
      - "80:80"
    volumes:
      - /opt/tftpboot:/tftpboot
      - /opt/tps/conf/tps.conf:/etc/httpd/conf.d/tps.conf
    restart: always
    tty: true
    privileged: true

  samba:
    image: tps-samba:1.0.0
    ports:
      - "139:139"
    volumes:
      - /opt/tftpboot:/tftpboot
      - /opt/tps/conf/smb.conf:/etc/samba/smb.conf
    restart: always
    tty: true
    privileged: true

  tftp:
    image: tps-tftp:1.0.0
    ports:
      - "69:69/udp"
    volumes:
      - /opt/tftpboot:/tftpboot
      - /opt/tps/conf/tftpd.map:/etc/tftpd.map
      - /opt/tps/conf/tftp:/etc/xinetd.d/tftp
    restart: always
    tty: true
    privileged: true

  nfs:
    image: tps-nfs:1.0.0
    ports:
      - "111:111"
      - "111:111/udp"
      - "2049:2049"
      - "2049:2049/udp"
      - "20048:20048"
      - "20048:20048/udp"
    volumes:
      - /opt/tftpboot:/tftpboot
      - /opt/tps/conf/exports:/etc/exports
    restart: always
    tty: true
    privileged: true
